const BASE = '/pm/api/marketing'

export async function getBrand() {
  const r = await fetch(`${BASE}/brand`)
  return r.json()
}

export async function saveBrand(brand) {
  await fetch(`${BASE}/brand`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(brand),
  })
}

export async function getCampaigns() {
  const r = await fetch(`${BASE}/campaigns`)
  return r.json()
}

export async function saveCampaign(campaign) {
  const r = await fetch(`${BASE}/campaigns`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(campaign),
  })
  return r.json()
}

export async function deleteCampaign(id) {
  await fetch(`${BASE}/campaigns/${id}`, { method: 'DELETE' })
}

export async function getHistory() {
  const r = await fetch(`${BASE}/history`)
  return r.json()
}

export async function saveHistory(record) {
  await fetch(`${BASE}/history`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(record),
  })
}

export async function deleteHistory(id) {
  await fetch(`${BASE}/history/${id}`, { method: 'DELETE' })
}

export async function streamRequest(endpoint, body, onChunk, onDone, onError) {
  let res
  try {
    res = await fetch(`${BASE}${endpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
  } catch (err) {
    onError(err.message); return
  }
  if (!res.ok) { onError(`HTTP ${res.status}`); return }

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buffer = ''

  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    buffer += decoder.decode(value, { stream: true })
    const lines = buffer.split('\n')
    buffer = lines.pop()
    for (const line of lines) {
      if (!line.startsWith('data: ')) continue
      const payload = line.slice(6)
      if (payload === '[DONE]') { onDone(); return }
      try {
        const { text, error } = JSON.parse(payload)
        if (error) { onError(error); return }
        if (text) onChunk(text)
      } catch {}
    }
  }
  onDone()
}

export async function sendEmail(to, subject, text) {
  const r = await fetch(`${BASE}/send-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ to, subject, text }),
  })
  if (!r.ok) throw new Error(`HTTP ${r.status}`)
  return r.json()
}

export function downloadAsPDF(title, content, meta) {
  const escaped = content.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:Georgia,'Times New Roman',serif;max-width:740px;margin:48px auto;padding:0 24px;color:#1a1a2e;line-height:1.8}
    .cover{border-bottom:2px solid #6366f1;padding-bottom:16px;margin-bottom:28px}
    h1{font-size:22px;font-weight:700;color:#0f0f23;margin-bottom:6px}
    .meta{font-size:12px;color:#6b7280;font-family:system-ui,sans-serif}
    .badge{display:inline-block;background:#ede9fe;color:#6d28d9;font-size:11px;font-weight:600;padding:2px 10px;border-radius:100px;margin-right:8px;font-family:system-ui,sans-serif}
    .content{font-size:14px;white-space:pre-wrap;word-break:break-word}
    .footer{margin-top:40px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;font-family:system-ui,sans-serif}
    @media print{body{margin:24px 32px}@page{margin:20mm}}
  </style>
</head>
<body>
  <div class="cover">
    <h1>${title}</h1>
    <div class="meta">${meta ? `<span class="badge">${meta}</span>` : ''}Generated by AI Project Manager &middot; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </div>
  <div class="content">${escaped}</div>
  <div class="footer">Smriti Chain LLC &middot; Marketing Assistant &middot; Powered by Multi-Provider AI</div>
</body>
</html>`
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const win = window.open(url, '_blank')
  if (win) win.addEventListener('load', () => { win.print(); setTimeout(() => URL.revokeObjectURL(url), 1000) })
}
